[workspace]
default-members = [
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
members = [
    "examples/*",
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
resolver = "3"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2024"
keywords = ["postgresql", "postgres", "embedded", "database", "server"]
license = "(Apache-2.0 OR MIT) AND PostgreSQL"
repository = "https://github.com/theseus-rs/postgresql-embedded"
rust-version = "1.94.0"
version = "0.21.1"

[workspace.dependencies]
anyhow = "1.0.104"
async-trait = "0.1.92"
axum = "0.8.9"
criterion = "0.8.2"
diesel = "2.3.13"
diesel_migrations = "2.3.2"
flate2 = "1.1.10"
futures-util = "0.3.34"
hex = "0.4.3"
indicatif = "0.18.6"
indoc = "2.0.7"
liblzma = "0.4.8"
md-5 = "0.11.0"
pgvector = "0.4.2"
postgres = "0.19.14"
quick-xml = "0.42.0"
rand = "0.10.3"
regex-lite = "0.1.9"
reqwest = { version = "0.13.5", default-features = false }
reqwest-middleware = "0.5.2"
reqwest-retry = "0.9.1"
reqwest-tracing = "0.7.1"
rustls = { version = "0.23.45", default-features = false }
semver = "1.0.28"
serde = "1.0.229"
serde_json = "1.0.151"
sha1 = "0.11.0"
sha2 = "0.11.0"
sqlx = { version = "0.9.0", default-features = false, features = ["postgres"] }
tar = "0.4.46"
target-tuple = "1.0.2"
tempfile = "3.27.0"
test-log = "0.2.21"
tokio = "1.53.1"
tracing = "0.1.44"
tracing-indicatif = "0.3.14"
tracing-subscriber = "0.3.23"
url = "2.5.8"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[workspace.lints.rust]
dead_code = "allow"
missing_debug_implementations = "deny"
unsafe_code = "deny"
unused_qualifications = "deny"
warnings = "deny"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
allow_attributes = "deny"
expect_used = "deny"
fallible_impl_from = "deny"
indexing_slicing = "deny"
mod_module_files = "deny"
panic = "deny"
panic_in_result_fn = "deny"
todo = "deny"
unreachable = "deny"
unimplemented = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
