name: Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: 'llvm-tools-preview'
          toolchain: stable

      - name: Install benchmarking tools
        uses: bencherdev/bencher@main

      - name: Run benchmarks
        if: ${{ github.event_name == 'pull_request' }}
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          BENCHER_PROJECT: theseus-rs-postgresql-embedded
          BENCHER_ADAPTER: rust_criterion
        run: |
          bencher run \
            --branch $GITHUB_HEAD_REF \
            --ci-number "${{ github.event.number }}" \
            --github-actions "${{ secrets.GITHUB_TOKEN }}" \
            --err \
            "cargo bench --features blocking"

      - name: Run benchmarks
        if: ${{ github.event_name != 'pull_request' }}
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          BENCHER_PROJECT: theseus-rs-postgresql-embedded
          BENCHER_ADAPTER: rust_criterion
        run: |
          bencher run "cargo bench --features blocking"
